Java 17
Ecwid/rest4j pull request #23
Opened 2021-09-29 12:00 UTC by Or4ng3

2021-10-04 08:42 UTC, Alexis2004 commented on core/src/main/java/com/rest4j/servlet/APIServlet.java
> +			ApiFactory apiFactory = new ApiFactory(xmlResource, pathPrefix, serviceProvider, null);
А что это за сервлет и почему здесь вместо cloner'а прокидывается null?

2021-10-04 08:43 UTC, Alexis2004 commented on core/src/test/java/com/rest4j/impl/MarshallerImplTest.java
> +	@Ignore
С чем связано игнорирование этих тестов?
Это починится в итоге? Если нет, то, наверное, стоит оставить пояснение

2021-10-04 08:43 UTC, Alexis2004 commented on core/src/test/java/com/rest4j/impl/UtilTest.java
> -	@Test public void testClone() {
Этот тест больше не нужен?

2021-10-04 08:45 UTC, Alexis2004 commented on core/src/test/java/com/rest4j/impl/petapi/Duplicable.java
> +public interface Duplicable<SubT> {
А чем Cloner отличается от Duplicable? Зачем нужно две похожих сущности?

2021-10-04 08:45 UTC, Alexis2004 requested changes
См. комменты и вопросы в изменённых файлах

2021-10-04 11:11 UTC, Or4ng3 commented on core/src/test/java/com/rest4j/impl/petapi/Duplicable.java
> +public interface Duplicable<SubT> {
Duplicable - интерфейс в тестах, а Cloner - в продакшен коде

----------------

Отличия в том что Cloner - общий интерфейс клонирования объектов, пришедших в запросах. Как его реализовывать - забота того кто подключил фреймворк к проекту. Хочешь сериализуй-десериализуй объект с помощью gson, хочешь руками обходи все поля и клонируй их значения. Зависит от фантазии автора. И не хочется тащить в продакшен код rest4j требование к реализации именно интерфейса Duplicable. Даже в нашем проекте, со временем, может поменяться механизм клонирования объектов

2021-10-04 11:14 UTC, Or4ng3 commented on core/src/test/java/com/rest4j/impl/UtilTest.java
> -	@Test public void testClone() {
Да, тест проверял работу метода Util.deepClone(test);. Теперь этого метода в коде нет. Забота о правильности клонирования лежит на плечах авторов проектов, подключивших фреймворк

2021-10-04 11:22 UTC, Or4ng3 commented on core/src/main/java/com/rest4j/servlet/APIServlet.java
> +			ApiFactory apiFactory = new ApiFactory(xmlResource, pathPrefix, serviceProvider, null);
В нашем коде сервлет не используется. Это, видимо, зашитый во фреймворк способ его настройки. У нас реализованы свои сервлеты.

Добавлять возможность прокинуть Cloner - не вижу смысла. А удалять класс жалко, вдруг пригодится, да и живем мы с ним уже долго

2021-10-04 11:39 UTC, Or4ng3 commented on core/src/test/java/com/rest4j/impl/MarshallerImplTest.java
> +	@Ignore
Залил фикс. Падение было связано с неготовностью тестового Clonner к таким тест кейсам

2021-10-11 10:44 UTC, Alexis2004 approved these changes

2021-10-11 10:44 UTC, merged